#!/bin/sh
cd /recalbox/share/themes/es-theme-next-pixel/
for d in * ; do
    echo "$d"
	index=2
	random=0
	#echo "/${d}_${index}" 
	while true
	do
		if [ -d "${d}_${index}" ]; then
			#echo "hello > ${d}_${index}"
			index=$((index+1))
		else 
			break
		fi
	done
	if(( $index > 2 )); then
		echo "index:${index}"
		random=$(( $RANDOM % (${index} - 1) + 1 ))
		echo $random
	fi
	if(( $random > 1 )); then
		mv $d temp
		mv "${d}_${random}" $d
		mv temp "${d}_${random}"
	fi
done
